"""added backref

Revision ID: 0443ca240814
Revises: b26e35ac4f24
Create Date: 2022-06-02 22:36:49.602125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0443ca240814'
down_revision = 'b26e35ac4f24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
