"""second

Revision ID: 12572728bcc3
Revises: e8594617198b
Create Date: 2022-05-22 11:31:48.459736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12572728bcc3'
down_revision = 'e8594617198b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('AuthSessions', schema=None) as batch_op:
        batch_op.drop_column('user_id')
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('api_key')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_key', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('AuthSessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.drop_column('id')
    # ### end Alembic commands ###
